---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mldky.
--- DateTime: 10.12.2023 10:03
--- For use in ComputerCraft
---

term.clear()
http.get("http://localhost:8000/comm.php?clientver=1.2")
data = http.get("http://localhost:8000/comm.php?version=1").readAll()
print(data)

function sendBlockData()
    downSuccess, down = turtle.inspectDown()
    if downSuccess then
        http.get("http://localhost:8000/comm.php?bottomname=" .. down.name)
    else
        http.get("http://localhost:8000/comm.php?bottomname=air")
    end
    forwardSuccess, forward = turtle.inspect()
    if forwardSuccess then
        http.get("http://localhost:8000/comm.php?forwardname=" .. forward.name)
    else
        http.get("http://localhost:8000/comm.php?forwardname=air")
    end
    upSuccess, up = turtle.inspectUp()
    if upSuccess then
        http.get("http://localhost:8000/comm.php?upname=" .. up.name)
    else
        http.get("http://localhost:8000/comm.php?upname=air")
    end
end

function sendLocationData()
    x, y, z = gps.locate()
    if x ~= nil then
        http.get("http://localhost:8000/comm.php?x=" .. x .. "&y=" .. y .. "&z=" .. z)
    else
        http.get("http://localhost:8000/comm.php?posnotfound=1")
    end
end

function sendInventoryData()
    for i = 1, 16 do
        turtle.select(i)
        data = turtle.getItemDetail()
        if data ~= nil then
            http.get("http://localhost:8000/comm.php?invslot=" .. i .. "&invname=" .. data.name .. "&invcount=" .. data.count)
        else
            http.get("http://localhost:8000/comm.php?invslot=" .. i .. "&invname=air&invcount=0")
        end
    end
end

while true do
    data = http.get("http://localhost:8000/comm.php").readAll()
    if data == "forward" then
        turtle.forward()
        sendBlockData()
        sendLocationData()
    elseif data == "backward" then
        turtle.back()
        sendBlockData()
        sendLocationData()
    elseif data == "up" then
        turtle.up()
        sendBlockData()
        sendLocationData()
    elseif data == "down" then
        turtle.down()
        sendBlockData()
        sendLocationData()
    elseif data == "left" then
        turtle.turnLeft()
        sendBlockData()
        sendLocationData()
    elseif data == "right" then
        turtle.turnRight()
        sendBlockData()
        sendLocationData()
    elseif data == "refreshinv" then
        sendInventoryData()
    elseif data == "select1" then
        turtle.select(1)
    elseif data == "select2" then
        turtle.select(2)
    elseif data == "select3" then
        turtle.select(3)
    elseif data == "select4" then
        turtle.select(4)
    elseif data == "select5" then
        turtle.select(5)
    elseif data == "select6" then
        turtle.select(6)
    elseif data == "select7" then
        turtle.select(7)
    elseif data == "select8" then
        turtle.select(8)
    elseif data == "select9" then
        turtle.select(9)
    elseif data == "select10" then
        turtle.select(10)
    elseif data == "select11" then
        turtle.select(11)
    elseif data == "select12" then
        turtle.select(12)
    elseif data == "select13" then
        turtle.select(13)
    elseif data == "select14" then
        turtle.select(14)
    elseif data == "select15" then
        turtle.select(15)
    elseif data == "select16" then
        turtle.select(16)

    elseif data == "update" then
        break
    end
    os.sleep(1)
end

print("Restarting...")