---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mldky.
--- DateTime: 10.12.2023 10:03
--- For use in ComputerCraft
---

term.clear()
http.get("http://localhost:8000/comm.php?clientver=1.12")
data = http.get("http://localhost:8000/comm.php?version=1").readAll()
print(data)

function sendBlockData()
    downSuccess, down = turtle.inspectDown()
    if downSuccess then
        http.get("http://localhost:8000/comm.php?bottomname=" .. down.name)
    else
        http.get("http://localhost:8000/comm.php?bottomname=air")
    end
    forwardSuccess, forward = turtle.inspect()
    if forwardSuccess then
        http.get("http://localhost:8000/comm.php?forwardname=" .. forward.name)
    else
        http.get("http://localhost:8000/comm.php?forwardname=air")
    end
    upSuccess, up = turtle.inspectUp()
    if upSuccess then
        http.get("http://localhost:8000/comm.php?upname=" .. up.name)
    else
        http.get("http://localhost:8000/comm.php?upname=air")
    end
end

function sendLocationData()
    x, y, z = gps.locate()
    if x ~= nil then
        http.get("http://localhost:8000/comm.php?x=" .. x .. "&y=" .. y .. "&z=" .. z)
    else
        http.get("http://localhost:8000/comm.php?posnotfound=1")
    end
end

function sendInventoryData()
    for i = 1, 16 do
        turtle.select(i)
        data = turtle.getItemDetail()
        if data ~= nil then
            http.get("http://localhost:8000/comm.php?invslot=" .. i .. "&invname=" .. data.name .. "&invcount=" .. data.count)
        else
            http.get("http://localhost:8000/comm.php?invslot=" .. i .. "&invname=air&invcount=0")
        end
    end
end

while true do
    data = http.get("http://localhost:8000/comm.php").readAll()
    if data == "forward" then
        turtle.forward()
        sendBlockData()
        sendLocationData()
    elseif data == "backward" then
        turtle.back()
        sendBlockData()
        sendLocationData()
    elseif data == "up" then
        turtle.up()
        sendBlockData()
        sendLocationData()
    elseif data == "down" then
        turtle.down()
        sendBlockData()
        sendLocationData()
    elseif data == "left" then
        turtle.turnLeft()
        sendBlockData()
        sendLocationData()
    elseif data == "right" then
        turtle.turnRight()
        sendBlockData()
        sendLocationData()
    elseif data == "refreshinv" then
        sendInventoryData()
    elseif data == "update" then
        break
    end
    os.sleep(1)
end

print("Restarting...")